#!/usr/bin/env php
<?php 
$host = '0.0.0.0';
$port = '3000';
$publicDir = __DIR__ . '/src';


if (!is_dir($publicDir)) {
    echo "Directory $publicDir does not exist.\n";
    exit(1);
}

echo "Starting PHP server at http://$host:$port\n";

$cmd = "php -S $host:$port -t " . escapeshellarg($publicDir);

passthru($cmd);